### PR TITLE
Fixed scintilla interface function signatures

### PR DESCRIPTION
**Pull request by mahee96**
- strictly typed C# enums were used instead of int (C/C++ enums are int)

### CODE REVIEW

**Comment by mahee96** [comment]
This PR#73 fixes#70

**Comment by mahee96** [comment]
@kbilsted merge this PR, and create a new release just in case for downloaders. The interface definitions are updated which may cause breaking changes to existing users/devs. 

Please release it with a **newer major release version number increment**.

**Comment by mahee96** [comment]
Issue #68 is related to same cause, of the 'int' being 32-bit signed integer in managed runtime irrespective of the word size of the processor as it is in unmanaged/native languages like C/C++ which the application Scintilla/Notepad++ is written in.

**Comment by mahee96** [comment]
There needs to be test cases and some more scenario to check how it works consistently than just making changes each time randomly.

Seems like day by day this project has started to become useful for others, will try to create some integration test via plugin. Or could we simply import notepad++'s plugin test cases for the integration tests?

**Comment by kbilsted** [comment]
its more difficult to test than I originally anticipated since some test require you to visually check the outcome.

I think I started some tests with executing against notepad and checking the resulting text buffer to verify the effect of the calls. Perhaps that is the best way forward but requires you to code some scaffolding for separating code into unit tests and executing them.

**Comment by mahee96** [comment]
we can start with adopting the plugin manager unit tests from notepad++ if any.

**Pull request closed without merging**
