### PR TITLE
Topic/sync scintillaiface

### PR DESCRIPTION
**Pull request by dail8859**
This is what I was referring to in #6. The main 2 Python files are straight from the Scintilla repo. The cs.py file is just something I threw together real quick. Running this will regenerate the Scintilla_iface.cs file. In theory if/when Notepad++ updates it's Scintilla version it is as easy as grabbing the new `.iface` file and rerunning `cs.py`.

I broke it up into 2 commits so you can see exactly how the Scintilla_iface.cs file is updated.

Feel free to do whatever you want with the PR. If you have another preferred way etc and don't want to use this PR I won't be offended. :)

### CODE REVIEW

**Comment by dail8859** [comment]
Also the Python file can easily be tweaked to generate stuff differently.

**Comment by kbilsted** [comment]
I guess I have to install Python now ;-)  I'll gladly look at it!

**Comment by dail8859** [comment]
Like you said the file is rarely changed. So one option might be to only keep the `Scintilla_iface.cs` file from this PR and from then on just manually update it whenever Notepad++ updates the `.iface` file.

**Comment by kbilsted** [comment]
well, now the work is done :-) I'll include it but change how it works slightly.

1. It will refer directly to the file in the NPP folder (the script will now expect you to clone NPP for this to work).. I think its less confusing
2. I'll rename the folder from scripts into something telling ordinary plugin devs. that they need not look in there.. 

Thanks for the update!

**Pull request merged**
