### PR TITLE
Added: GetScrollInfo functionality for the Scintilla main view

### PR DESCRIPTION
**Pull request by nea**
Hi

As I required the current windows scroll information, I added the _user32_ method **GetScrollInfo()** to grab the information from a given handle. I added it to the ScintillaGateway to use it based on that handle.

To have the struct and match the flags for the call, I added the according structs and enums to the _Win32_ class.

It is nothing crucial to the functionality of this plugin. Especially if not looking for it. But I wanted to use/try it and thought it may come in handy with others ^^

Best

### CODE REVIEW

**Comment by kbilsted** [comment]
great! will look at it within 2 weeks along with the other PR

**Comment by kbilsted** [comment]
One thought. Since it is impossible to provide unit tests for this kind of project (plugin integration) what I do is test features manually in the demo plugin. Thus, I was wondering it would make sense to extend the demo plugin with reading the scrollinfo such that I and others can test that it actually is working :-)

**Comment by nea** [comment]
Hey kbilsted

Yeah, I thought about that but couldn't think of something sensible in the sense of the Demo Plugin. But maybe two menu entries jump to end, jump to start or printing the scroll-percentage . . . I will think of something ^^


Cheers

**Comment by kbilsted** [comment]
Sounds like good ideas ;)

**Comment by kbilsted** [comment]
Are you working on a feature in the demo to test the functionality?

**Comment by nea** [comment]
Yes, I am :)

**Comment by nea** [comment]
Hey @kbilsted 

I added a new menu entry to print the newly gained scroll and row information, depending on the current Notepad++ window size and scrolling. 


Cheers

**Comment by kbilsted** [comment]
Sorry for the delay. I hope I can do something on it in the weekend..

**Pull request merged**
