### PR TITLE
Fixes for the Scintilla syncronizer

### PR DESCRIPTION
**Pull request by jokedst**
* Sets IntPtr where needed
* use 'length' parameters as buffer size (GetText, GetCurLine)

Includes newly generated files. No post-generation fixes needed anymore.

### CODE REVIEW

**Comment by kbilsted** [comment]
@mahee96 can you have a look at this PR also?

**Comment by mahee96** [comment]
Yeah sure.

**Comment by kbilsted** [comment]
I hardcoded the length to 10.000 to make things easy. It did not take long before that limit was underestimated. See also  https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/pull/28 where @dail8859  had some good observations on using `SendMessage()`

**Comment by mahee96** [comment]
@kbilsted I reviewed the commits, and **see no new changes required** except for the length issue fix, which I think we can follow up in PR #28 

_Some notes about review:_
Scintilla_iface.cs (No visible code changes)
ScintillaGateway.cs (IntPtr change is already merged commit 23ec20f38219c66115591ab984950fb65cec23bd , **object length issue** can be tracked in PR #28 review and I will test it in my system)
IScintillaGateway.cs(IntPtr is change - merged)
cs.py(IntPtr is change - merged)

I think this PR can be closed now.

**Comment by kbilsted** [comment]
#28 never fixed anything real and refer back to here :)

**Comment by mahee96** [comment]
@kbilsted Sorry, what I meant to say is, we can track the **dynamic string length** issue in the open issue/PR #28(has a commit and tries to do the same thing which is done here - and requires more testing) **and close this one** instead of keeping this one open(redundant).

The usage of length needs to be tested based on what @dail8859 had mentioned in PR #28(implicit call to get length, when not supplied) and will be better if we cover it with that thread in PR #28

**Comment by mahee96** [comment]
closing the PR as mentioned above.

**Pull request closed without merging**
